### ISSUE TITLE
derive(Error) with Backtrace causes errors on beta

### ISSUE THREAD

**Issue by Heliozoa** [dtolnay/thiserror#204]
Hi,
Thanks for your work on thiserror.

I'm trying to use `std::backtrace::Backtrace` with thiserror now that `std::backtrace` is available on beta, but I'm getting a couple of errors.

https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=e66ea95c9e0f2b4bea73d1cb4b503716
```rs
Compiling playground v0.0.1 (/playground)
error[[E0432]](https://doc.rust-lang.org/beta/error-index.html#E0432): unresolved import `thiserror`
 --> src/lib.rs:5:10
  |
5 | #[derive(Error, Debug)]
  |          ^^^^^ no `ThiserrorProvide` in `__private`
  |
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[[E0658]](https://doc.rust-lang.org/beta/error-index.html#E0658): use of unstable library feature 'error_generic_member_access'
 --> src/lib.rs:5:10
  |
5 | #[derive(Error, Debug)]
  |          ^^^^^
  |
  = note: [see issue #99301 <https://github.com/rust-lang/rust/issues/99301>](https://github.com/rust-lang/rust/issues/99301) for more information
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

error[[E0599]](https://doc.rust-lang.org/beta/error-index.html#E0599): no method named `thiserror_provide` found for reference `&std::io::Error` in the current scope
  --> src/lib.rs:10:9
   |
10 |         source: io::Error,
   |         ^^^^^^ method not found in `&std::io::Error`

Some errors have detailed explanations: E0432, E0599, E0658.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `playground` due to 3 previous errors
```

I saw that there are other similar issues posted, but they seem to be related to rust-analyzer, and given that this is reproduceable on the playground I felt fairly confident that this is a new issue.

**Comment by dtolnay** [comment]
Rust 1.65 (current beta) only stabilizes the Backtrace **type**, not any of the functionality for using backtraces with the Error trait. You can't use backtraces in an error until the rest is stabilized as well.

**Comment by lvaroqui-gpfw** [comment]
Just my 2 cents, but I was really confused that all backtraces related features didn't work on stable (1.65 as of today). I think there should be a disclaimer in the docs until this hits stable.

**Comment by miaomiao1992** [comment]
dear sir
     I use rust-nightly-1.68，and the codes referred to 'backtrace' also don't work.


error[E0658]: use of unstable library feature 'error_generic_member_access'
 --> src\error\error.rs:7:10
  |
7 | #[derive(Error, Debug)]
  |          ^^^^^
  |
  = note: see issue #99301 <https://github.com/rust-lang/rust/issues/99301> for more information
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by miaomiao1992** [comment]
dear sir
     i use rust-nightly-1.68, and the codes referred to 'backtrace' also don't wok.

error[E0658]: use of unstable library feature 'error_generic_member_access'
 --> src\error\error.rs:6:10
  |
6 | #[derive(Error, Debug)]
  |          ^^^^^
  |
  = note: see issue #99301 <https://github.com/rust-lang/rust/issues/99301> for more information
  = help: add `#![feature(error_generic_member_access)]` to the crate attributes to enable
  = note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0658`.
error: could not compile `actix-learn` due to previous error
